### ISSUE TITLE
Question: grantlee i18n support

### ISSUE THREAD

**Issue by buschmann23** [cutelyst/cutelyst#13]
What is the way to use the the i18n support of Grantlee? Support for the i18n tags is compiled in, "grantlee_i18ntags.so" plugin is available, but simply using i18n "some string" is not working with the following warning:

> "Invalid block tag on line 0: 'i18n''. Did you forget to register or load this tag?"

Ho do I have to register or load it? I can not find any documentation about it. (Not meening that it is not there. ;) )

Do I have to load the QLocalizer of Grantlee to use the i18n tags even without any translation files?

**Comment by dantti** [comment]
Hmm there are 2 issues for this to work actually, the first is that Grantlee::Engine seems to need grantlee_i18ntags to be loaded:
`engine->addDefaultLibrary(QStringLiteral("grantlee_i18ntags"));`
This is currently not possible as Grantlee View doesn't expose the Engine pointer I could do that, but even doing this the error persisted so I'm going to poke Grantlee author to see if he ca explain why.
The second issue is that you need to define a localizer for the Grantlee::Context, which is also not possible and is actually a bit more complex to do as you need to set it for **every** request, one can't set the application locale globally since it might be running in threaded mode or in async mode, the best way to solve this issue would be too add a new API a QLocale in Cutelyst::Context, with some sort of plugin that can extract it from Request Headers, Url path ("example.com/pt_BR/somethin") or Session token, I just didn't find time to deal with this yet. Hopefully in 1.3.0 :)

**Comment by dantti** [comment]
I've just pushed the API change to expose Grantlee::Engine, still the second issue and the load i18ntags plugin remains.

**Comment by dantti** [comment]
And I've changed Grantlee::View to check if a "locale" stash key is defined and set the context localizer, so a code like:
http://www.catalystframework.org/calendar/2006/18
You would just need to do `c->setStash("locale", QLocale(...));` instead of c->language([ ... ])
would work quite easily, it would still be interesting to have some way to define the locale in context but this doesn't need API changes ATM.

**Comment by buschmann23** [comment]
I now played a bit around with translating Grantlee template files. The current implementation with simply creating a Grantlee::QtLocalizer object does not work, it needs information about the translation files, otherwise it will fall back to QCoreApplication::translate(). I created #22 PR to add QTranslator for available locales to the QtLocalizer in GrantleeView::render().

**Comment by dantti** [comment]
Can I close this one?

**Comment by buschmann23** [comment]
Yes :)
