### ISSUE TITLE
Segfault if application fails to load engine

### ISSUE THREAD

**Issue by simonaw** [cutelyst/cutelyst#132]
If you return false in the `MyApp::init()` member the last output of `cutelyst2 --server --app-file libMyApp.so` is
```
default[fatal] Main engine failed to init
Aborted (core dumped)
```
The thing is if I change the `qFatal()` to `std::cerr` in `wsgi/wsgi.cpp`, function `setupApplication()` (to be exact [here](https://github.com/cutelyst/cutelyst/blob/571cc93216c7787a2a4e5e56cf8db494faab07f2/wsgi/wsgi.cpp#L1381)) I don't get the Segfault any more but the application seems to hang and does not respond to any signals. What gives?

**Comment by dantti** [comment]
Your application must return true in init() and postFork(). If it returns false is because it failed to start and thus keeping it running will prevent you from from fixing what went wrong.
Imagine that systemd starts you app that required a db connection but it fails to open, if you don't finish you application systemd will think it's running fine and won't report an error to the user. You will only notice it's not working when you try to access the application.

**Comment by dantti** [comment]
Right, so that you can install the driver and have it work properly.

Do you mean that false on postFork() will keep it respawning? I thought I had fixed this to "cheap" the worker, maybe when I changed to qFatal instead of exit it broke.

**Comment by simonaw** [comment]
Yes, exactly!  I normally start the development server like this:
`cutelyst2 --server --restart --server-port 3000 --app-file build/src/libMyApp.so`
when I return false in `init()` I get:
```
DAMN ! worker 1 (pid: 8800) died, killed by signal 0 :( trying respawn ..
Respawned WSGI worker 1 (new pid: 8807, cores: 1)
```
over and over again. Leaving out the `--restart` argument I get the already mentioned Segfault.

**Comment by dantti** [comment]
please test it it works properly now, thanks.

**Comment by simonaw** [comment]
Yes! ¡Excelente! :+1: 
Thanks.
