### ISSUE TITLE
Using cutelyst-wsgi2.exe as a system service

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#174]
Hello! Have you considered transforming cutelyst-wsgi2.exe into cross-platform system service?
I mean using Cutelyst without reverse proxy for small/medium projects in local network, for example.
For example, could [QtService](https://github.com/Skycoder42/QtService) be helpful? 
I'd like to start and stop REST service even in Windows ('cause Cutelyst disables stopping in Windows).

**Comment by dantti** [comment]
What do you mean by Cutelyst disables stoppin in Windows?
And the only reason to use reverse proxy is if you need virtual hosts, otherwise you can just serve HTTP directly, it is in fact the fastest option, which I do on a few projects...

**Comment by arietto** [comment]
I mean this:
`#ifdef Q_OS_UNIX
    QCommandLineOption stopOption(QStringLiteral("stop"),
                                  QCoreApplication::translate("main", "stop an instance"),
                                 QCoreApplication::translate("main", "pidfile"));
//... 
#endif

**Comment by arietto** [comment]
I don't ask you to add system service mode, just I'd like to know your opinion about benefits/disadvantages.

**Comment by dantti** [comment]
ah that's why I don't know Windows, I still need to add hooks to grab their process signals and send them, but on a GUI app you can call start() stop() no problem there, on Linux in fact I don't even use this command line method because systemd service will already send the required signal, so perhaps Windows can also deal with that too
