### ISSUE TITLE
CredentialPassword::createPassword and salt

### ISSUE THREAD

**Issue by sibbi77** [cutelyst/cutelyst#175]
CredentialPassword::createPassword pays attention to the number of salt bytes saltByteSize (at least on platforms other than Windows). But it converts the random values (of cryptographic quality) into a base64 encoded version and uses that to feed CredentialPassword::pbkdf2.
The salt is therefore longer, but less random than requested.

Is this intentional? and is this a good idea?

**Comment by dantti** [comment]
what is different?

**Comment by sibbi77** [comment]
Let's do it line by line:
calling `CredentialPassword::createPassword( "password", QCryptographicHash::Sha512, 10000, 16, 16);`
results in the creation of `salt = random.read(saltByteSize).toBase64();`
Cutelyst creates the requested number of random bytes, but directly stretches the array to 24 bytes (base64). This salt is then handed over to pbkdf2().
The caller of createPassword() expected to use a 16 byte salt with pbkdf2, but Cutelyst uses a less random 24 byte salt. That's not entirely wrong, but unexpected, because pbkdf2() can work with binary data (does not need base64 encoded strings).

**Comment by dantti** [comment]
pbkdf2 does work with binary data, it's not less random because base64 is just another representation.
if you look at:
https://github.com/cutelyst/cutelyst/blob/master/Cutelyst/Plugins/Authentication/credentialpassword.cpp#L161
you have the salt returned to the caller, which is needed to compute the password again an see if it matches, if I feed the binary data to pkdf2 when I try to check the password I'll need to convert from base64 to binary and do the check, which is fine but will break applications.
I can't really argue on what is best, perhaps what you said, but this will break existing applications, in fact even for say "cutelyst 3" this introduces a breakage...
