### ISSUE TITLE
make TestEngine a public API 

### ISSUE THREAD

**Issue by Talkless** [cutelyst/cutelyst#176]
Hi,

I see `tests/coverageobject.h` has infrastructure to allow testing endpoints. 

It would be useful to have TestEngine (and all other relevant code) in public, "official" Cutelyst API, to test our http requests/responses with QtTest framework, probably without mandatory Coverage support or any other Cutelyst-test-specifics.

**Comment by dantti** [comment]
It's an interesting idea, if you can provide a PR where this class/API is available outside Core would be great.

**Comment by mike23456** [comment]
Hi @dantti 
May I ask about the status of this issue. we would like to write unit tests for a large number of controllers and I want to do it right from the start to minimize refactoring. Looked into this code and i think we can use TestEngine and createRequest().

is there any better option available?

I've recently coded in C# for a few months and liked the use of Interfaces and Moq for mocking almost any class including REST API calls. Therefore, I decided to do a similar thing in c++ so I created abstract classes in c++ (like interfaces in C#) and used a c++ Dependency Injection library called Kangaru to easily inject concrete classes anywhere. 
For example i created an AbstractSqlQueryFactory and a concrete implementation and passed that via Dependency Injection.
When writing tests I can easily replace the SqlQueryFactory with a SqlQueryFactoryMock which returns fake query results without hitting the db.

Now the questions is, do u think any of the above can make Cutelyst testing easier?

**Comment by mike23456** [comment]
Hi again, thanks @dantti for the quick reply. Definitely need to export TestEngine but we have another problem:
 
Unit tests are meant to be small and focused on testing a single unit of code in isolation.   
Suppose i have a function doSomething() inside users_POST which is part of Users Controller. I want to test doSomething() as a single unit in isolation.  However, doSomething() takes 2 parameters a Cutelyst::Context and Cutelyst::Sql::Transaction.

During testing I want to be able to pass a  fake Cutelyst::Context and a fake Cutelyst::Sql::Transaction to doSomething().
Therefore Context should inherit AbstractContext instead of QObject. same for Sql::Transaction.

Can we add those Abstract Classes to Cutelyst?

**Comment by mike23456** [comment]
@dantti  
> Can we add those Abstract Classes to Cutelyst?

Hi Daniel. I know u might be super busy. Just let me know your opinion about the above and our team can work on it then raise a PR for the changes.

**Comment by dantti** [comment]
@mike23456 hi, sorry, you can Create a fake Cutelyst::Context, but I'm not really sure adding a bunch of abstracts will be a nice option, esp due more vtables.
