### ISSUE TITLE
Easy to deploy - linuxdeployqt support

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#188]
Hello! According to https://cutelyst.org/ this framework is "Easy to deploy".
Can you describe some steps in order to deploy pure cutelyst-wsgi2 (without custom Controllers) to another Linux server? I've tried linuxdeployqt, but failed.

    #!/bin/sh
    export LD_LIBRARY_PATH=/home/elias/projects/current/cutelyst-bin/lib/x86_64-linux-gnu:/home/elias/Qt/5.12.1/gcc_64/lib:/home/elias/projects/current/cutelyst-bin/lib:$LD_LIBRARY_PATH
    /home/elias/Downloads/linuxdeployqt-6-x86_64.AppImage /home/elias/projects/current/cutelyst-bin/bin/cutelyst-wsgi2 -qmake=/home/elias/Qt/5.12.1/gcc_64/bin/qmake

**Comment by dantti** [comment]
it's easy to deploy because you can simply copy you .so file or binary (if you include the WSGI module) to the server, and as long as you have compatible Qt/Cutelyst/OS/Architecture it's a single file copy. As oposed to copying a bunch of controllers code, dbi, and what not.

I don't know linuxdeployqt tool.

**Comment by dantti** [comment]
closing this as I don't plan to support linuxdeployqt, I can accept a PR if someone adds.
Thanks
