### ISSUE TITLE
How to solve the symbol lookup error?

### ISSUE THREAD

**Issue by xvlinihao** [cutelyst/cutelyst#206]
I am trying to use the get request to get some information from the url 'api/ac/*' , but the terminal output that
 
9912:9912 cutelyst.request[debug] "GET" request for "api/ac/234" from "::1"
9912:9912 cutelyst.dispatcher[debug] Path is "api/ac"
9912:9912 cutelyst.dispatcher[debug] Arguments are "234"
cutelyst2: symbol lookup error: ./src/libServerREST.so: undefined symbol: _ZN5ApiAc6RoomIdEPN8Cutelyst7ContextERK7QString

So what does this mean?  I am sorry to trouble you again , but as a newbie to web framework and cutelyst2, I really can't solve this problem on my own. Can you give me some resolutions to this? Many thanks

**Comment by dantti** [comment]
That usually means you are missing the .cpp implementation of ApiAc::RoomID(Cutelyst::Context, QString).
If you added this as a new file, using the CMakeFiles.txt provided by cutelyst2 --create-app you probably need to run cmake .. on the build directory for it to notice new files, otherwise that .cpp file won't be compiled and you will also have this error.

**Comment by xvlinihao** [comment]
I‘ve already solved this problem, I find that I had this problem because I just declared ApiAc::RoomID but forgot to give definition to it. Thank you all the same, great appreciation for your quick reply.
