### ISSUE TITLE
Qt license and cutelyst?

### ISSUE THREAD

**Issue by overthetop** [cutelyst/cutelyst#240]
Can I use cutelyst in comersial projects? Qt is not free. Can you please help me understand better?
For a redit thread (https://www.reddit.com/r/programming/comments/803fx9/qt_commercial_vs_free_question_in_comment/)  I saw this:

> Qt is available under LGPL, GPL or with a commercial license. You can choose which one you want to use.
> 
> LGPL basically means your users have the right to modify the Qt part of your application. If you modify Qt itself, your users have to be able to get that modified code, so they can modify it further. Additionally there has to be a way for them to use their modified Qt library with your application. Usually this is done by dynamic linking: You use a qt.dll and the user can replace it with their own modified qt.dll.
> 
> GPL means your users have the right to modify you whole application, not just the Qt part.
> 
> With the commercial license you don't have these restrictions. You can keep your modifications to Qt private and your application doen't need to be able to used a Qt library modified by the user.

Having a http server running Qt makes it not possible for users to modify Qt lib. Does that mean that I have to buy Qt commercial?

**Comment by dantti** [comment]
First, Qt is free.
Second yes you can use it in commercial projects, the LGPL states that if you sell your application binary, the user must be able to replace the Qt part there, as well as the Cutelyst part because Cutelyst is also LGPL. Doesn't matter if it's static or dynamic linking.
Now, you are running a server that isn't AGPL so anyone connecting to your server isn't covered by LGPL, which is why AGPL was created, so even if Qt and Cutelyst were GPL (not AGPL) HTTP users wouldn't have the right to get your sources.

**Comment by dantti** [comment]
And also in this case your local changes to Qt or Cutelyst doesn't even need to be made public or given back if they are kept private in your company servers and are not sold to anyone. Any free software that is kept private inside a company can be modified without exposing the changes.

**Comment by overthetop** [comment]
thank you @dantti
