### ISSUE TITLE
Eventloop threading problem

### ISSUE THREAD

**Issue by sibbi77** [cutelyst/cutelyst#273]
I've created a stripped down simple testcase based on the Hello tutorial code: https://github.com/sibbi77/cutelyst-tutorial

I'm using one QThread object within a multithreaded application providing a service (e.g. sending mail). To send a mail, a worker thread calls the slot Mailer::sendMail() as a normal member function. To execute Mailer::sendMail() in the correct threading context I check thread() against QThread::currentThread() and if they disagree, I call QMetaObject::invokeMethod() with an explicit Qt::QueuedConnection flag.

This is a fairly standard and proven and simple procedure to make sure the function is executing in its own thread.

Now the problem with cutelyst:

If I call the Hello application like this:
`cutelyst-wsgi2 --application BUILD/src/libHello.so --threads 2 --processes 0 --h1 0.0.0.0:8080`
Everything is working and I get the log message `96910:96911 Mailer[debug] void Mailer::sendMail(QString, QString, QVariantHash) now running in correct thread` as expected.

But, if I call the Hello application like this:
`cutelyst-wsgi2 --application BUILD/src/libHello.so --threads 2 --h1 0.0.0.0:8080 --master`
Cutelyst forks to create a child (children). BTW most combinations of --threads and --processes result in an abort `98312:98312 wsgi.tcp_server_balancer[critical] Failed to bind to socket 9`, but that is another problem. Using the fork option, the function is no longer executed correctly.

Why has forking an impact on internal event creation/delivery with QMetaObject::invokeMethod()?

I'm totally lost here. Do you have an idea what's going on here?

Cutelyst v2.12.0 (happens with older, too)
Qt 5.12.8 (happens with older, too)
Ubuntu 20.04 (happens with 18.04, too)

Just to recap the main point: QMetaObject::invokeMethod() returns true, i.e. it says it created the event to call the function and the function exists, but it is never called. I also created a timer running inside the thread, to check, if event loop dispatching is working correctly; it is.

**Comment by dantti** [comment]
If you want to to send mail, I highly recommend using simplemailqt in async mode, that way you don't need to worry about threads.

Now, if you don't use --lazy your application be loaded 2 times, then forks 1 process (due --master) and create 2 threads to deal with those two applications that were created before forking.
It's very important to notice that forking a process with threads running is not safe.
So if you create your threads on constructor rather than on postFork() methods they will simply stop working and might even freeze you app entirely.
About the failed to bind I recommend using --reuse-port, sometimes the listen is left blocking new listen due stabilished connections, not sure how to fix that.

**Comment by dantti** [comment]
and looking at your code that's exactlly the mistake I told you.
Threads, db connections all sorts of data that should not be shared amonst process must always got in postFork().

**Comment by sibbi77** [comment]
Thanks for your quick response! I'm actually using postFork for my database connection and some other stuff, but was unaware of this threading thing with fork. I've never done this in my own code...

It's working like a charm now, that I moved the code to postFork().

Thanks!
