### ISSUE TITLE
FastCGI socket and multiple threads

### ISSUE THREAD

**Issue by buschmann23** [cutelyst/cutelyst#38]
Using a local FastCGI socket together with multiple threads like in the following cutelyst-wsgi call
```
cutelyst-wsgi -M -t auto --fastcgi-socket /run/myapp.sock --chown-socket myuser:www --socket-access ug --uid myuser --gid mygroup --pidfile /run/myapp.pid  -a /path/to/libmyapp.so
```
Fails either directly or after a while for some of the threads with the following error message:
```
21504:21508 default[warning] QSocketNotifier: Invalid socket 6 and type 'Read', disabling...
21504:21506 default[warning] QSocketNotifier: Invalid socket 6 and type 'Read', disabling...
21504:21510 default[warning] QSocketNotifier: Invalid socket 6 and type 'Read', disabling...
```
In the example above six threads have been started. Three of them failed directly after first socket access with the above messages. Socket is accessed by Apache via `ProxyPass`.

Using multiple processes, each with on thread, will not fail with the above error.

**Comment by dantti** [comment]
interesting, I'll try to reproduce, does it also fails on client side or is it just this message?

**Comment by dantti** [comment]
Ok, managed to reproduce, and as a workaround you can use TCP sockets which worked fine. Not sure yet why it happens, but once that message is out it stops working :sob:

**Comment by buschmann23** [comment]
Yes. Same for me. After that message, nothing happens any more. Apache than returns a 502 error. Currently I am using the FastCGI socket with multiple processes, that works fine. :)

**Comment by dantti** [comment]
Ok, this seems to be a complex issue, I dunno why in earlier versions it worked, but be it threads or process it seems that when a thread/processes gets the connection and the other one get's an invalid value which end up on that message, which I'm not sure yet how makes QLocalServer delete it's socket file. Odd that I recall this working when I first added the UNIX socket feature... ATM I'd recommend using TCP ...

**Comment by buschmann23** [comment]
Hm, when I try it with multiple processes I get no error, but after a while only one process of six seems to be active and reacts to requests. (tested with wieghttp and siege)

**Comment by dantti** [comment]
Ok, it's a Qt bug, and indeed it can happen with process too.
Basically if accept fails due the other thread/process accepting it then it will close the server and delete the socket file, then that message is emitted because the FD QSocketNotifier was watching is now invalid, since I run Cutelyst on AWS with a single core CPU and using a single process this issue didn't hit me.

I can implement the experimental-thread-balance for local sockets which will fix the issue for threaded apps...

I'll be opening a bug report and eventually I'll fix it myself since my QtNetwork bugs usually stay there for a while.
