### ISSUE TITLE
Question: cutelyst app in subdirectory

### ISSUE THREAD

**Issue by buschmann23** [cutelyst/cutelyst#42]
Is it somehow possible to run a Cutelyst application in a subdirectory like `http://www.example.com/myapp/`?

Or where would be the entry point to implement this in the application?

**Comment by dantti** [comment]
It's not possible to have dynamic entry points. But that doesn't mean you can't write your application on a /myapp namespace, if you are using Path dispatcher using C_NAMESPACE on each controller would be enough, if you are using the Chained dispatcher then each method has to be chained to /myapp.

Catalyst doesn't support this feature, and afaik many other frameworks such as Ruby on Rails.

In principle it's not that hard, for on Path dispatcher it could prepend the prefix to each Action, on Chained it would probably be a bit more complex, this wouldn't bring any performance issue.

The problem is c->uriFor() might need to take that into account which might make it a little slower, and your application would break if you use absolute paths on your templates and doesn't use c->uriFor().

Also I don't have plans to think/add this right now, websockets is my priority ATM.

**Comment by buschmann23** [comment]
That is how I thought it. :)
