### ISSUE TITLE
epoll_ctl() failed (No such file or directory)

### ISSUE THREAD

**Issue by buschmann23** [cutelyst/cutelyst#44]
I tried to activate the epoll event dispatcher and got the following critical error. So, now I am not sure if it is a compilation error of mine or if I am enabling it the wrong way.

cutelyst-wsgi command line:
```
CUTELYST_EVENT_LOOP_EPOLL=true QT_LOGGING_RULES=*.debug=true cutelyst-wsgi --ini /path/to/myapp.ini -a /path/to/myapp.so --uid myuser --gid mygroupdi --h1 127.0.0.1:3000
```

Error:
```
868:4868 cutelyst.core[info] Skaffari powered by Cutelyst 1.6.0, Qt 5.7.1.
spawned WSGI worker 1 (pid: 4870, cores: 6)
4870:4870 [critical] void EventDispatcherEPollPrivate::unregisterSocketNotifier(QSocketNotifier*): epoll_ctl() failed (No such file or directory)
4870:4870 wsgi[debug] Starting threads
```

After killing it (Ctrl + C):
```
CSIGINT/SIGQUIT received, killing workers...
4868:4868 default[critical] void EventDispatcherEPollPrivate::wake_up_handler(): internal error, testAndSetRelease(1, 0) failed!
Memory access error
```

Environment:
Linux 4.10.13
glibc 2.25
Qt 5.7.1
Cutelyst 1.6.0

**Comment by dantti** [comment]
Not an compilation error of yours.

    4870:4870 [critical] void EventDispatcherEPollPrivate::unregisterSocketNotifier(QSocketNotifier*): epoll_ctl() failed (No such file or directory)

The above happens because after fork() I delete a QSocketNotifier, but epoll is open with CLOEXEC so it's not initialized nor would be responsible for the FD we are trying to unregister.

In fact I'm not sure how efficient epoll is when --master (fork) and without threads, because when you use threads a new event loop is created for each thread. I mean that I dunno because it might not be working at all due fork(), but I didn't have tested and debuged this enough.

There are also some more messages that popup when stating/shutting down, so IMHO you should avoid it on production due some possible unexpected behavior.

Since I didn't wrote it, I'm not very familiar with it yet.
