### ISSUE TITLE
Document applicability to coexisting w/ GUI desktop application

### ISSUE THREAD

**Issue by Phrogz** [cutelyst/cutelyst#47]
Cutelyst is recommended in various spots on the Web where people are asking, _~"How can I write one Qt application that can be used on both Desktop/Mobile and via web browser?"_

I assume that this would require using completely separate view code for Desktop (e.g. QML) versus web (e.g. Grantlee), and so the only code re-use would be any application logic.

This issue is both a request to clarify that my assumption is correct, and also that you proactively document this for future people evaluating Cutelyst with a similar goal in mind.

**Comment by dantti** [comment]
Cutelyst is a Web Framework, Web speaks HTTP and presentation is done via HTML, JS and some browsers are starting to support WebAssemby, so together with projects like http://qtandeverything.blogspot.com.br/2017/06/qt-for-web-assembly.html you can indeed write a single code, since you still need to serve HTTP.

Again Cutelyst is a Web Framework, and in no place it's stated that it's meant to make desktop applications run in a web browser, what it's said is that you can **share** code, this misconception is probably due people thinking Qt is GUI only toolkit which it's not.
