### ISSUE TITLE
Configuration of a mere generated Hello app is failing on Windows

### ISSUE THREAD

**Issue by texpert** [cutelyst/cutelyst#52]
There is a `cutelystqt5-config.cmake` and it is located in the `\cutelyst\build` folder, but the configuration is failing:

```
C:\cutelyst\build\Debug>cd build

C:\cutelyst\build\Debug\Hello\build>cmake ..
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindCutelystQt5.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CutelystQt5", but CMake did not find one.

  Could not find a package configuration file provided by "CutelystQt5" with
  any of the following names:

    CutelystQt5Config.cmake
    cutelystqt5-config.cmake

  Add the installation prefix of "CutelystQt5" to CMAKE_PREFIX_PATH or set
  "CutelystQt5_DIR" to a directory containing one of the above files.  If
  "CutelystQt5" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incom
rate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
See also "C:/cutelyst/build/Debug/Hello/build/CMakeFiles/CMakeOutput.log".
```

**Comment by texpert** [comment]
Here I made it - https://github.com/cutelyst/cutelyst/pull/54, @dantti 

Though, the Wiki needs some additions in regards to building and running on Windows. Could do it later, if you're accepting the PR.

**Comment by dantti** [comment]
The Wiki ATM if free to everyone to edit, so be welcome :)

**Comment by dantti** [comment]
Closing this as mentioned on the PR

**Comment by ccassan** [comment]
Hello,
I see that this issue is closed but I still have issues with the training  as of 01/10/2018 on windows.
It complained about not finding CuteLystQt5Config.cmake, on my install it is called CuteLyst2Qt5Config.cmake. I went further by renaming the file, and generated the Hello code. Now it fails at the cmake .. command, not finding Cutelyst2Qt5Targets.cmake.

D:\CuteLyst\MyTests\Hello\build>cmake ..
CMake Error at D:/CuteLyst/cutelyst/build/CutelystQt5Config.cmake:13 (include):
  include could not find load file:

    D:/CuteLyst/cutelyst/build/Cutelyst2Qt5Targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:16 (find_package)

This file exists on my machine but under D:\CuteLyst\cutelyst\build\CMakeFiles\Export\_usr\lib\cmake\Cutelyst2Qt5
I'm not familiar with cmake, should this file have been moved when I compiled cutelyst? The compilation seemed ok.

Thanks for your help

**Comment by dantti** [comment]
Cutelyst master branch is v2.0 you should use v1.x.x branch ATM

**Comment by ccassan** [comment]
Thank you, it worked better with the branch.
The training info on the wiki is targeting Linux, with references to .so and such, so it doesn’t work out of the box but I should be able to find my way through it.
Thanks

**Comment by Plaristote** [comment]
Seems like the v2 is stable now, yet this issue still is valid. I've got the same issue with that missing Cutelyst2Qt5Targets.cmake file, referenced by Cutelyst2Qt5Config.cmake... is that file supposed to exist, and what's supposed to generate it ?

I've been using Qt 5.12 and msvc2017. Clearly not an entirely supported setup, considering Cutelyst doesn't compile out of the box with Qt 5.12 (minor issue due to the lack of Qt::endl in earlier versions of Qt). Still, it would be pretty damn handy to me if I could properly link my projects to Cutelyst in that environment.
