### ISSUE TITLE
Cutelyst and cutelyst-wsgi license

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [cutelyst/cutelyst#70]
Hello!

Would you kindly explain how is the Cutelyst is licensed?

The README.md mentions, that the library is licensed under LGPLv2+. And it is fine for me because I can create closed-source applications without license violation as long as Cutelyst is dynamically linked. However, header comments in source and header files say, that the library is licensed under GPLv2.

So the question is: what is the real license of Cutelyst?

And as a consequence of this question: what is the license of cutelyst-wsgi? The sources mention GPLv2. And that is the moment I become confused: technically, the application I develop is a shared library, loaded by cutelyst-wsgi. Does it matter, that the application must be licensed under GPLv2 as well to use it with the cutelyst-wsgi server?

Thanks in advance!

Best regards,
Innokentiy

**Comment by dantti** [comment]
2017-11-23 14:50 GMT-02:00 Innokentiy Alaytsev <notifications@github.com>:
>
> Hello!

Hi!
>
> Would you kindly explain how is the Cutelyst is licensed?
>
> The README.md mentions, that the library is licensed under LGPLv2+. And it is fine for me because I can create closed-source applications without license violation as long as Cutelyst is dynamically linked. However, header comments in source and header files say, that the library is licensed under GPLv2.

Thanks for looking into this, the cpp and .h files actually have a
LGPL2.0 preamble, I'll replace all for LGPL2.1.
And BTW you can also make closed source application statically linking
to Cutelyst as long as you provide a way
to relink with another Cutelyst build.

>
> So the question is: what is the real license of Cutelyst?

LGPL2.1+ specially chosen to allow closed-source apps, also I hope to
be able to keep using Qt 5.6 for a long time as it was the last
LGPLv2.1+ version.


> And as a consequence of this question: what is the license of cutelyst-wsgi? The sources mention GPLv2. And that is the moment I become confused: technically, the application I develop is a shared library, loaded by cutelyst-wsgi. Does it matter, that the application must be licensed under GPLv2 as well to use it with the cutelyst-wsgi server?

cutelyst-wsgi actually has 2 licenses :D
As a library it is LGPLv2.1+ so that you can use it on your own
executable and actually
replace cutelyst-wsgi (executable) with your own including not needing
to load your app from a plugin.
As a executable it is GPLv2.1+ but it is really a simple main file, I
might change that to BSD or something
if I found it's an issue to load closed plugins in it, because it
really is just a main.cpp to use the library....


>
> Thanks in advance!
>
> Best regards,
> Innokentiy
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




-- 
Daniel Nicoletti

KDE Developer - http://dantti.wordpress.com

**Comment by Innokentiy-Alaytsev** [comment]
Hello!

Thanks for quick reply!

You have really reassured me, because as far as I see, there is no alternative for Cutelyst that is good enough for my taste, and it would be a disaster to be unable to use such a wonderful tool.

Hope I will be able to contribute)

Best wishes,
Innokentiy

**Comment by dantti** [comment]
You are already contributing...
Having Cutelyst as GPL like Wt open source version is wouldn't attract users IMO,

**Comment by Innokentiy-Alaytsev** [comment]
I totally agree with you. The GPL license of open-source version of Wt is the reason why I didn't even try it. As well as QxOrm and ODB for database access. Unfortunately I am a poor developer of commercial project)

**Comment by dantti** [comment]
@buschmann23 I'm pushing a commit to update the headers that have my name on it, can you please do the same with yours? Thanks.

**Comment by buschmann23** [comment]
Yes, will change it.
